---
# tbd
# - name: Dump an existing database to a file
#   community.postgresql.postgresql_db:
#     name: test_db
#     state: dump
#     target: /tmp/test_db.sql

- name: Include EnterPrice vars
  ansible.builtin.include_vars:
    file: eps_vars.yml
    name: eps_vars

- name: Copy dumped files from source to target host
  ansible.builtin.copy:
    remote_src: false
    src: "{{ eps.vars.postgresql_tmp_eps_dir }}"
    dest: "{{ eps_vars.postgresql_dump_dir }}"
    owner: "{{ postgresql_dir_owner }}"
    group: "{{ postgresql_dir_owner }}"
    mode: "{{ postgresql_file_permissions }}"
