---
- name: Stop PostgreSQL service if it exists
  ansible.builtin.systemd_service:
    name: postgresql-{{ postgresql_version }}
  register: postgresql_state

- name: Uninstall PostgreSQL server
  ansible.builtin.dnf:
    name:
      - postgresql{{ postgresql_version }}-server
    state: absent
    disable_gpg_check: true

- name: Remove PostgreSQL directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ postgresql_dirs }}"
