---
# roles/postgresql/handlers/main.yml
- name: Include EnterPrice vars
  ansible.builtin.include_vars:
    file: eps_vars.yml
    name: eps_vars

- name: Clean up dir
  ansible.builtin.file:
    path: "{{ eps_vars.postgresql_tmp_eps_dir }}"
    state: absent

- name: Debug register name
  ansible.builtin.debug:
    var: pgsql_initdb

- name: Restart PostgreSQL Service
  ansible.builtin.systemd_service:
    name: postgresql-{{ postgresql_version }}-{{ item.item.instance_name }}
    state: restarted
    daemon_reload: true
    enabled: true
  loop: "{{ pg_hba_changed.results }}"
